# Importing Dataset

In [5]:
import os
os.chdir("C:/Users/Abhi Matlapudi/Desktop/ML-Project Cars")

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
cars = pd.read_csv("auto-mpg.csv")

In [8]:
cars

,%mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,Engine Fuel Type
0,18.0,8,307.0,130,3504.0,12.0,70.0,1,chevrolet chevelle malibu,premium unleaded (required)
1,15.0,8,350.0,165,3693.0,11.5,70.0,1,buick skylark 320,premium unleaded (required)
2,18.0,8,318.0,150,3436.0,11.0,70.0,1,plymouth satellite,premium unleaded (required)
3,16.0,8,304.0,150,3433.0,12.0,70.0,1,amc rebel sst,premium unleaded (required)
4,17.0,8,302.0,140,3449.0,10.5,70.0,1,ford torino,premium unleaded (required)
...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790.0,15.6,82.0,1,ford mustang gl,regular unleaded
394,44.0,4,97.0,52,2130.0,24.6,82.0,2,vw pickup,regular unleaded
395,32.0,4,135.0,84,2295.0,11.6,82.0,1,dodge rampage,regular unleaded
396,28.0,4,120.0,79,2625.0,18.6,82.0,1,ford ranger,regular unleaded
397,31.0,4,119.0,82,2720.0,19.4,82.0,1,chevy s-10,regular unleaded